# Generated by Django 4.2.3 on 2023-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_coursecontent_content_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontent",
            name="content_link",
            field=models.CharField(max_length=500),
        ),
    ]
