# Generated by Django 4.2.3 on 2024-04-09 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_option_question_quiz_userresponse_question_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="userresponse",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="ResponseAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.option"
                    ),
                ),
                (
                    "user_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.userresponse",
                    ),
                ),
            ],
        ),
    ]
