# Generated by Django 4.2.3 on 2024-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0011_remove_userresponse_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
